# This workflow is used during feature development, it will perform lightweight CI.

name: Feature Development

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'

permissions: {}

jobs:
  terraform-plan-prd:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    environment: Production
    runs-on: ubuntu-latest

    concurrency: # This is required to prevent multiple GitHub Actions invocations against stateful resources. e.g. Terraform state file / Database / Deployed Apps
      group: ${{ github.repository }}-prd

    steps:
      - uses: actions/checkout@v6

      - uses: frasermolyneux/actions/terraform-plan@terraform-plan/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        env:
          TF_VAR_github_service_connection_pat: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION_PAT }}
          AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
