name: PR Verify

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

permissions: {}

jobs:
  terraform-plan-prd:
    permissions:
      contents: read
      id-token: write
    if: github.event.pull_request.draft == false
    environment: Production
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-prd
    env:
      AZURE_CLIENT_ID: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && vars.AZURE_PLAN_CLIENT_ID || vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
      - uses: frasermolyneux/actions/terraform-plan@main
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          terraform-additional-args: "-var github_service_connection_pat=${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION_PAT }}"
          AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        env:
          AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
